# Pipeline for reference TOC generation

trigger: none
pr: none
schedules:
- cron: 0 11 * * *
  displayName: Daily TOC generation at 6 AM EST
  branches:
    include:
    - jasonjoh/toc-gen

resources:
  repositories:
  - repository: msgraph-toc-gen
    type: github
    name: microsoftgraph/msgraph-toc-gen
    ref: main
    endpoint: github.com_jasonjoh
  - repository: AD-AggregatorService-Workloads
    type: git
    name: One/AD-AggregatorService-Workloads
    ref: master
    endpoint: MSAzure/One

pool:
  vmImage: ubuntu-latest

variables:
  tocGeneratorPath: $(Build.SourcesDirectory)/msgraph-toc-gen/src
  tocGeneratorProject: $(tocGeneratorPath)/GenerateTOC.csproj
  tocGeneratorApp: $(tocGeneratorPath)/bin/Release/net8.0/GenerateTOC
  referenceRoot: $(Build.SourcesDirectory)/microsoft-graph-docs/api-reference
  v1ReferenceRoot: $(referenceRoot)/v1.0
  betaReferenceRoot: $(referenceRoot)/beta
  workloadsFolderPath: $(Build.SourcesDirectory)/AD-AggregatorService-Workloads/Workloads

stages:
- stage: GenerateTOC
  displayName: Generate reference TOC
  jobs:
  - job: GenerateTOC
    displayName: Generate reference TOC
    steps:
    - checkout: self
      displayName: Checkout docs repo
      persistCredentials: true

    - checkout: msgraph-toc-gen
      displayName: Checkout TOC generator repo

    - checkout: AD-AggregatorService-Workloads
      displayName: Checkout workloads repo

    - task: UseDotNet@2
      displayName: Install .NET SDK 8
      inputs:
        version: 8.x

    - task: DotNetCoreCLI@2
      displayName: Build TOC generator project
      inputs:
        command: build
        projects: $(tocGeneratorProject)
        arguments: '--configuration Release'

    - pwsh: $(tocGeneratorApp) --api-docs $(v1ReferenceRoot)/api --resource-docs $(v1ReferenceRoot)/resources --csdl $(workloadsFolderPath) --mapping $(v1ReferenceRoot)/toc/toc.mapping.json --terms-override $(referenceRoot)/toc.terms.overrides.json --toc $(v1ReferenceRoot)/toc.yml --static-toc $(v1ReferenceRoot)/toc/static-toc.yml
      displayName: Generate v1 reference TOC

    - pwsh: $(tocGeneratorApp) --api-docs $(betaReferenceRoot)/api --resource-docs $(betaReferenceRoot)/resources --csdl $(workloadsFolderPath) --mapping $(betaReferenceRoot)/toc/toc.mapping.json --terms-override $(referenceRoot)/toc.terms.overrides.json --toc $(betaReferenceRoot)/toc.yml --static-toc $(betaReferenceRoot)/toc/static-toc.yml --api-version beta
      displayName: Generate beta reference TOC

    - pwsh: |
        git config user.email "GraphTooling@service.microsoft.com"
        git config user.name "Microsoft Graph DevX Tooling"
      displayName: Configure git
      workingDirectory: $(Build.SourcesDirectory)/microsoft-graph-docs

    - pwsh: |
        $status = git status --porcelain
        if ($status -eq $null) {
          Write-Host "No changes to commit." -ForegroundColor Green
        } else {
          $timestamp = Get-Date -Format FileDateTimeUniversal
          git checkout -b toc-gen/$timestamp
          git add .
          git commit -m "Generated reference TOC"
          git push --set-upstream origin toc-gen/$timestamp
        }
      workingDirectory: $(Build.SourcesDirectory)/microsoft-graph-docs
      displayName: Commit and push TOC updates
